version: '3.3'

services:
  courier-api:
    build: ./app
    image: courier-api:1.0
    container_name: courier-api-1.0
    restart: unless-stopped
    # env_file: "./app/.env"
    # ports:
    #   - 8080:5000
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      - "postgres"
    volumes:
      - log:/home/courier_api/logs


  postgres:
    image: postgres:12.6-alpine
    container_name: postgres-12.6
    restart: unless-stopped
    # env_file: "./app/.env"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: courier_api

  nginx:
    build: ./nginx
    # image: courier-api:1.0
    container_name: nginx-1.18.0
    restart: unless-stopped
    # env_file: .env
    ports:
      - 8080:8080
    # environment:
    #   POSTGRES_USER: $POSTGRES_USER

    #   POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      - "courier-api"

volumes:
  log:
